---
authors:
  - Seiko Solutions Inc.
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: 'LICENSE'
name: smartcs
namespace: seiko
description: Ansible Network Collection for Seiko SmartCS devices
readme: README.md
repository: https://github.com/ssol-smartcs/ansible-collections
issues: https://github.com/ssol-smartcs/ansible-collections/issues
documentation: https://github.com/ssol-smartcs/ansible-collections/tree/main/seiko.smartcs/docs
homepage: https://www.seiko-sol.co.jp/en/products/console-server/console-server_automation/ansible/
tags: [seiko, smartcs, networking]
version: 1.7.0-dev5

build_ignore:
  - venv
  - 'galaxy.yml'
  - '*__pycache__'
  - '__pycache__'
  - '*.bak'
  - '*.tar'
  - '*.pyc'
  - '*.svn'
  - '*.retry'
  - '*.git'
